In [10]:
import pandas as pd
import textwrap
test = pd.read_csv("data/ground-truth/QA-Dataset.csv")
test.head()

,question,answer
0,Pasien dengan Jenis kelamin: Perempuan Usia: 1...,"STRONGKids, PNRS, SGNA, dan STAMP merekomendas..."
1,Pasien dengan Jenis kelamin: Perempuan Usia: 1...,Gizi Baik (BB/PB -2 SD sd +1\nSD) dengan peraw...
2,Pasien dengan Jenis kelamin: Perempuan Usia: 1...,"Jumlah leukosit terdeteksi sebesar 11,63 × 10³..."
3,Pasien dengan Jenis kelamin: Perempuan Usia: 1...,NI-1.1 Peningkatan kebutuhan Energi berkaitan ...
4,Pasien dengan Jenis kelamin: Perempuan Usia: 1...,Memenuhi kebutuhan energi dan protein yang men...

In [15]:
file_path = "outputs/2025-10-02_14-45-50/result_semantic_2025-10-02_144609.csv"
test_csv = pd.read_csv(file_path)
test_csv

,user_input,retrieved_contexts,response,reference,context_precision,context_recall,faithfulness,answer_relevancy,bleu,rouge1,rouge2,rougeL
0,Pasien dengan Jenis kelamin: Perempuan Usia: 1...,['Jenis Kelamin \n \n: perempuan \nUsia (bula...,"BB: 8,9 kg TB: 73 cm LILA: - LK: - dan diagnos...","STRONGKids, PNRS, SGNA, dan STAMP merekomendas...",0.0,0.000,0.200000,0.245917,1.914603e+00,0.095238,0.0,0.095238
1,Pasien dengan Jenis kelamin: Perempuan Usia: 1...,['Jenis Kelamin \n \n: perempuan \nUsia (bula...,"BB: 8,9 kg TB: 73 cm LILA: - LK: - dan diagnos...",Gizi Baik (BB/PB -2 SD sd +1\nSD) dengan peraw...,0.0,0.000,0.333333,0.348353,1.260631e+00,0.062500,0.0,0.062500
2,Pasien dengan Jenis kelamin: Perempuan Usia: 1...,['Ka \nJenis Kelamin \n \n: Perempuan \nUmur...,Diagnosis medis yang ditegakkan oleh dokter ad...,"Jumlah leukosit terdeteksi sebesar 11,63 × 10³...",1.0,0.875,0.333333,0.609544,1.151485e-13,0.015564,0.0,0.015564
3,Pasien dengan Jenis kelamin: Perempuan Usia: 1...,['Jenis Kelamin \n \n: perempuan \nUsia (bula...,TB Paru + Pneumonia + Gizi Buruk Marasmus,NI-1.1 Peningkatan kebutuhan Energi berkaitan ...,0.0,0.000,0.500000,0.527982,9.654444e-13,0.008772,0.0,0.008772
4,Pasien dengan Jenis kelamin: Perempuan Usia: 1...,['Nama Pasien \nUsia \n(Thn) \nRuangan \nDiagn...,"BB: 8,9 kg TB: 73 cm LILA: - LK: - dan diagnos...",Memenuhi kebutuhan energi dan protein yang men...,0.0,0.800,0.333333,0.237190,1.075512e+00,0.042553,0.0,0.042553

In [ ]:
with open("outputs/results.md", "w", encoding="utf-8") as f:
    for i, row in test_csv.head().iterrows():
        f.write(f"# Question {i+1}\n\n")
        f.write(f"## User Question\n{row['user_input']}\n\n")
        f.write(f"## Generated Answer\n{row['response']}\n\n")
        f.write(f"## Ground Truth Answer\n{row['reference']}\n\n")
        f.write(f"## Retrieved Chunks\n")
        if isinstance(row["retrieved_contexts"], list):
            for chunk in row["retrieved_contexts"]:
                f.write(f"- {chunk}\n")
        else: 
            f.write(f"{row['retrieved_contexts']}\n")
        f.write("\n---\n\n")